// <auto-generated />
using System;
using LinkBakery.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LinkBakery.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220410192417_AddNewBaseValuesToAllTables")]
    partial class AddNewBaseValuesToAllTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.2.22153.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LinkBakery.Domain.Entities.TrackingLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("RedirectWithQueryParameter")
                        .HasColumnType("bit");

                    b.Property<string>("TargetUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TrackingLinks");
                });

            modelBuilder.Entity("LinkBakery.Domain.Entities.TrackingLinkCall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("QueryParameter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrackingLinkId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrackingLinkId");

                    b.ToTable("TrackingLinkCalls");
                });

            modelBuilder.Entity("LinkBakery.Domain.Entities.TrackingLinkCall", b =>
                {
                    b.HasOne("LinkBakery.Domain.Entities.TrackingLink", "TrackingLink")
                        .WithMany("TrackingLinkCalls")
                        .HasForeignKey("TrackingLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrackingLink");
                });

            modelBuilder.Entity("LinkBakery.Domain.Entities.TrackingLink", b =>
                {
                    b.Navigation("TrackingLinkCalls");
                });
#pragma warning restore 612, 618
        }
    }
}
